services:
    idp:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB_URL_HOST: database
            KC_DB_URL_PORT: 3306
            KC_DB_URL_DATABASE: keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: keycloak
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
        networks:
            - proxy
            - default
        command: [ "start-dev", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false"] #"--log-level=DEBUG,org.hibernate:ERROR,io.quarkus:ERROR"]
        volumes:
            - ./theme/theme/voucherr:/opt/keycloak/themes/voucherr

    database:
        image: mariadb:11.4
        environment:
            MYSQL_USER: 'keycloak'
            MYSQL_PASSWORD: 'keycloak'
            MYSQL_DATABASE: 'keycloak'
            MYSQL_RANDOM_ROOT_PASSWORD: "true"

networks:
    proxy:
        external: true
